server:
  port: 8083
  session-timeout: 30
  ##tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
#  servlet:
#    context-path: /template3

spring:
    profiles: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        master:
           name: test
           url: jdbc:mysql://localhost:3306/template?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
           username: root
           password: root
           driver-class-name: com.mysql.jdbc.Driver
           filters: stat
           maxActive: 20
           initialSize: 1
           maxWait: 60000
           minIdle: 1
           timeBetweenEvictionRunsMillis: 60000
           minEvictableIdleTimeMillis: 300000
           validationQuery: select 'x' FROM DUAL
           testWhileIdle: true
           testOnBorrow: false
           testOnReturn: false
           poolPreparedStatements: true
           maxOpenPreparedStatements: 20
    thymeleaf:
      cache: false
mapper:
    mappers: tk.mybatis.mapper.common.Mapper
    identity: select sys_guid() from dual
    order: before
#指定日志输入级别
logging:
  level: info




---
########################################################
###THYMELEAF (ThymeleafAutoConfiguration)
########################################################
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        cache: false
        cache-period: 0

---


logging:
  level:
     com.qilinxx.kuding : info
#上传文件大小不限制
 # spring.servlet.multipart.max-file-size=-1
  #spring.servlet.multipart.max-request-size=-1
spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    favicon:
      enabled: false
