spring:
  application:
    name: consumer-user
server:
  port: 8200
eureka:
  instance:
    prefer-ip-address: true #注册服务时，使用ip地址
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/